//Skill Parser (c)from elementskill.dll v1.7.4

/* SKILL DESCRIPTION BEGIN */
/*
11950  "N/A致盲（废弃）"11951  "N/A^ffffff致盲　　　　　　　　　　　　　等级%d

^ffcb4a施放距离　^ffffff近身
^ffcb4a消耗真气　^96f5ff%d^ffffff
^ffcb4a准备时间　^ffffff0.4　^ffcb4a�?^ffcb4a施放时间　^ffffff1.2　^ffcb4a�?^ffcb4a施放间隔　^ffffff8.0　^ffcb4a�?^ffcb4a武器限制　^ffffff匕首

^ffcb4a修真期要求　^ffffff和合
精确的刺杀技巧，对敌人造成基础物理攻击�?附加^96f5ff%.1f^ffffff的物理伤害�?并且打断对方当前技能�?18150  "Reckless Rush"18151  "^ffff00Reckless Rush

^ffcb4aRange　^96f5ff15^ffcb4a　meters
^ffcb4aMana　^96f5ff141^ffffff
^ffcb4aChannel　^ffffffInstant
^ffcb4aCooldown　^ffffff90.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffUnarmed, Blade, Sword, Poleblade, Pike, Club, Axe, Poleaxe, Hammer, Polehammer

^ffcb4aRequired Cultivation　^ffffffAware of Vacuity
During the war with the Winged Elves, the Humans developed a highly effective technique
that allowed them to quickly close in on their enemies. Though the Humans and Winged Elves
now live in peace, this technique is still taught to young blademasters.

Charge instantly to your foe, immobilizing your target for ^96f5ff3^ffffff seconds and
dealing ^96f5ff120%%^ffffff of base physical damage. If your enemy's Health is below ^96f5ff50%%^ffffff,
this attack deals ^96f5ff2^ffffff times as much damage. Cannot be a critical strike, but
has a chance of twice your Critical Rate to deal ^96f5ff1.5^ffffff times as much damage.

^a6caf0Costs ^ffffff50^a6caf0 Chi.
"18160  "Blade Tornado"18161  "^80ff00Blade Tornado^a0ff00^b0ff00^bfff00^e0ff00^ffff00

^ffcb4aMana　^96f5ff495^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.7　^ffcb4aseconds
^ffcb4aCooldown　^ffffff180.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffUnarmed, Melee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of Vacuity
Create a whirling tempest of fiery rage
for ^96f5ff12^ffffff seconds, slashing out every ^96f5ff3^ffffff
seconds at all enemies within ^96f5ff10^ffffff meters.
Deals ^96f5ff450%%^ffffff of weapon damage and slows
targets by ^96f5ff30%%^ffffff for ^96f5ff3^ffffff seconds. Reduces
incoming damage by ^96f5ff50%%^ffffff and makes you
immune to all control effects. Deals
^96f5ff12000^ffffff to ^96f5ff20000^ffffff additional damage based
on your Soulforce. Cannot be a critical
strike, but has a chance of twice your
Critical Rate to deal ^96f5ff1.5^ffffff times as much
damage. Recharges ^96f5ff2^ffffff Sparks over the duration^96f5ff^ffffff.

^a6caf0Costs ^ffffff3^a6caf0 Sparks.

"18170  "Flame Tsunami"18171  "^ffff00Flame Tsunami

^ffcb4aRange　^ffffffMelee
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff0.9　^ffcb4aseconds
^ffcb4aCooldown　^ffffff120.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffUnarmed, Melee weapons


^ffcb4aRequired Cultivation　^ffffffAware of Vacuity

Draw power from your wounds to unleash a torrent
of fire. Only usable when your Health is below ^96f5ff75%%^ffffff.
Burns all enemies in a ^96f5ff12^ffffff meter line, dealing base
physical damage plus ^96f5ff200%%^ffffff of weapon damage plus ^96f5ff7200^ffffff
and stunning targets for ^96f5ff3^ffffff Never misses.

"18180  "Blade Hurl"18181  "^ffff00Blade Hurl

^ffcb4aRange　^96f5ff25^ffcb4a　meters
^ffcb4aMana　^96f5ff353^ffffff
^ffcb4aChannel　^ffffff0.2　^ffcb4aseconds
^ffcb4aCast　^ffffff0.9　^ffcb4aseconds
^ffcb4aCooldown　^ffffff60.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons

^ffcb4aRequired Cultivation　^ffffffAware of Vacuity

Throw your weapon in a wide arc, disarming you
for ^96f5ff3^ffffff seconds and all enemies within ^96f5ff8^ffffff meters
for ^96f5ff6^ffffff seconds. Deals base physical damage plus
^96f5ff100%%^ffffff of weapon damage plus ^96f5ff3500^ffffff. Never misses.

^a6caf0Costs ^ffffff35^a6caf0 Chi."18190  "Reel In"18191  "^ffff00Reel In

^ffcb4aRange　^96f5ff25^ffffff　^ffcb4ameters
^ffcb4aMana　^96f5ff212^ffffff
^ffcb4aCast　^ffffff2.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff120.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons, Unarmed

^ffcb4aRequired Cultivation　^ffffffAware of Vacuity
Channel a line of energy from your weapon to
pull an enemy toward you. The success chance is
^96f5ff40%%^ffffff, ^96f5ff70%%^ffffff, or ^96f5ff100%%^ffffff against higher, equal, or lower-
level targets respectively, and is affected by Soulforce.

^a6caf0Costs ^ffffff50^a6caf0 Chi.




"18680  "8706856"18681  "The skill generated by Chaos: Sword Cyclone"18710  "Sword Cyclone"18711  "^ffff00Sword Cyclone

^ffcb4aMana　^96f5ff392^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.7　^ffcb4aseconds
^ffcb4aCooldown　^ffffff300.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons, Unarmed

^ffcb4aRequired Cultivation　^ffffffAware of Vacuity
Create a whirling tempest of
fiery rage for ^96f5ff12^ffffff seconds,
slashing out every ^96f5ff3^ffffff seconds at
all enemies within ^96f5ff10^ffffff meters.
Deals ^96f5ff200%%^ffffff of weapon damage and
makes you immune to all control
effects for the duration. Deals
^96f5ff2500^ffffff to
^96f5ff6500^ffffff additional damage
based on your Soulforce. Recharges
^96f5ff2^ffffff Sparks over the ^96f5ff12^ffffff second duration.

^a6caf0Costs ^ffffff3^a6caf0 Sparks."18720  "8706857"18721  "The skill of Sword Cyclone."22060  "ΦFerocious Leap"22061  "^ffff00ΦFerocious Leap

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aCast　^ffffff1.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff3.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff20
^ffcb4aWeapon　^ffffffMelee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Leap at your foe with an animalistic fury,
dealing base physical damage plus ^96f5ff2825^ffffff.
Causes the target to bleed for ^96f5ff3^ffffff seconds, dealing
an additional ^96f5ff300%%^ffffff of weapon damage plus ^96f5ff%d^ffffff.

^f7dfa5Sage version generates ^96f5ff20^f7dfa5 Chi."22070  "ΩFerocious Leap"22071  "^ffff00ΩFerocious Leap

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aCast　^ffffff1.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff3.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff15
^ffcb4aWeapon　^ffffffMelee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Leap at your foe with an animalistic fury,
dealing base physical damage plus ^96f5ff2825^ffffff.
Causes the target to bleed for ^96f5ff3^ffffff seconds, dealing
an additional ^96f5ff300%%^ffffff of weapon damage plus ^96f5ff%d^ffffff.

^d618e7Demon version increases bleed damage by ^96f5ff100%%^d618e7 of weapon damage."22080  "ΦArmy Crusher"22081  "^ffff00ΦArmy Crusher

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aCast　^ffffff1.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff3.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff10
^ffcb4aWeapon　^ffffffMelee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Sweep your weapon in a massive arc, delivering
a powerful attack against all enemies within ^96f5ff10^ffffff
meters, dealing base physical damage plus ^96f5ff7241^ffffff.

^f7dfa5Sage version deals an additional ^96f5ff1825^f7dfa5 damage."22090  "ΩArmy Crusher"22091  "^ffff00ΩArmy Crusher

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aCast　^ffffff1.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff3.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff10
^ffcb4aWeapon　^ffffffMelee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Sweep your weapon in a massive arc, delivering
a powerful attack against all enemies within ^96f5ff12^ffffff
meters, dealing base physical damage plus ^96f5ff5416^ffffff.

^d618e7Demon version increases the range to ^96f5ff12^d618e7 meters."22100  "ΦRiver Avalanche"22101  "^ffff00ΦRiver Avalanche

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.8　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff10
^ffcb4aWeapon　^ffffffMelee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Fall upon your enemy with the power of a crashing wave, dealing base physical damage plus ^96f5ff140%%^ffffff of
weapon damage plus ^96f5ff4664^ffffff. Has a ^96f5ff55%%^ffffff chance to stun the target for ^96f5ff3^ffffff seconds. Increases your Threat.

^f7dfa5Sage version deals ^96f5ff180%%^f7dfa5 of weapon damage."22110  "ΩRiver Avalanche"22111  "^ffff00ΩRiver Avalanche

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.8　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff10
^ffcb4aWeapon　^ffffffMelee Weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Fall upon your enemy with the power of a crashing wave, dealing base physical damage plus ^96f5ff140%%^ffffff of
weapon damage plus ^96f5ff4664^ffffff. Has a ^96f5ff55%%^ffffff chance to stun the target for ^96f5ff3^ffffff seconds. Increases your Threat.

^d618e7Demon version reduces the cooldown by ^96f5ff1^d618e7 second."23520  "ΦFarstrike"23521  "^ffff00ΦFarstrike

^ffcb4aRange　^96f5ff20^ffffff　^ffcb4aMeters
^ffcb4aMana　^96f5ff165^ffffff
^ffcb4aChannel　^ffffff0.5　^ffcb4aseconds
^ffcb4aCast　^ffffff0.8　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff10
^ffcb4aWeapon　^ffffffPoleblade, Pike, or Club

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Magically empower your weapon to strike a distant
foe. Deals base physical damage plus ^96f5ff150%% ^ffffffof weapon
damage plus ^96f5ff6918^ffffff. If the target is more than ^96f5ff10 ^ffffffmeters away,
it will be stunned for ^96f5ff3 ^ffffffseconds. If the target is within ^96f5ff10 ^ffffffmeters,
it will receive additional base physical damage.
Cannot be a critical strike.


^f7dfa5Sage version increases damage by ^96f5ff60%% ^f7dfa5of weapon damage plus ^96f5ff1200^f7dfa5."23670  "ΩFarstrike"23671  "^ffff00ΩFarstrike

^ffcb4aRange　^96f5ff20^ffffff　^ffcb4aMeters
^ffcb4aMana　^96f5ff165^ffffff
^ffcb4aChannel　^ffffff0.5　^ffcb4aseconds
^ffcb4aCast　^ffffff0.8　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff10
^ffcb4aWeapon　^ffffffPoleblade, Pike, or Club

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Magically empower your weapon to strike a distant
foe. Deals base physical damage plus ^96f5ff150%% ^ffffffof weapon
damage plus ^96f5ff6918^ffffff. If the target is more than ^96f5ff10 ^ffffffmeters away,
it will be stunned for ^96f5ff3 ^ffffffseconds. If the target is within ^96f5ff10 ^ffffffmeters,
it will receive additional base physical damage.
Cannot be a critical strike.

^d618e7Demon version generates ^96f5ff20 ^d618e7Chi.
^d618e7Demon version never misses."23680  "ΦSpirit Chaser"23681  "^ffff00ΦSpirit Chaser

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff140^ffffff
^ffcb4aChannel　^ffffff0.5　^ffcb4aseconds
^ffcb4aCast　^ffffff0.7　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff50
^ffcb4aWeapon　^ffffffBlade or Sword

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Summon shadow blades to rapidly strike the enemy.
Deals base physical damage plus ^96f5ff300%%^ffffff of weapon damage plus
^96f5ff7712^ffffff. This attack is guaranteed to hit.

^f7dfa5Sage version reduces the channel time by ^96f5ff0.2^f7dfa5 seconds."23690  "ΩSpirit Chaser"23691  "^ffff00ΩSpirit Chaser

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff140^ffffff
^ffcb4aChannel　^ffffff0.5　^ffcb4aseconds
^ffcb4aCast　^ffffff0.7　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff50
^ffcb4aWeapon　^ffffffBlade or Sword

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Summon shadow blades to rapidly strike the enemy.
Deals base physical damage plus ^96f5ff300%%^ffffff of weapon damage
plus ^96f5ff7712^ffffff. This attack is guaranteed to hit.

^d618e7Demon version generates ^96f5ff60^d618e7 Chi."23700  "ΦStar Smite"23701  "^ffff00ΦStar Smite

^ffcb4aRange　^96f5ff8^ffffff　^ffcb4ameters
^ffcb4aMana　^96f5ff165^ffffff
^ffcb4aChannel　^ffffff0.3　^ffcb4aseconds
^ffcb4aCast　^ffffff0.8　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff30
^ffcb4aWeapon　^ffffffPolearm, Pike, Club, Blade, or Sword

^ffcb4aRequired Cultivation　^ffffffMaster of Harmony
Throw your weapon at all targets in a ^96f5ff25^ffffff meter
line, dealing base physical damage plus ^96f5ff5115^ffffff.
Knocks non-player targets back ^96f5ff18^ffffff meters.
Never misses.

Polearms, Pikes, and Clubs increase the range to ^96f5ff20^ffffff meters,
and deal an additional ^96f5ff100%%^ffffff of weapon damage.
Blades and Swords deal melee damage plus ^96f5ff300%%^ffffff of weapon damage.

^f7dfa5Sage version also interrupts the target."23710  "ΩStar Smite"23711  "^ffff00ΩStar Smite

^ffcb4aRange　^96f5ff8^ffffff　^ffcb4ameters
^ffcb4aMana　^96f5ff165^ffffff
^ffcb4aChannel　^ffffff0.3　^ffcb4aseconds
^ffcb4aCast　^ffffff0.8　^ffcb4aseconds
^ffcb4aCooldown　^ffffff6.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff30
^ffcb4aWeapon　^ffffffPolearm, Pike, Club, Blade, or Sword

^ffcb4aRequired Cultivation　^ffffffMaster of Discord
Throw your weapon at all targets in a ^96f5ff25^ffffff meter
line, dealing base physical damage plus ^96f5ff5115^ffffff.
Knocks non-player targets back ^96f5ff18^ffffff meters.
Never misses.

Polearm, Pikes, and Clubs increase the range to ^96f5ff20^ffffff meters,
and deal an additional ^96f5ff100%%^ffffff of weapon damage.
Blades and Swords deal melee damage plus ^96f5ff300%%^ffffff of weapon damage.

^d618e7Demon version hobbles targets for ^96f5ff8^d618e7 seconds, lowering their Evasion by ^96f5ff50%%^d618e7."23720  "ΦHillborn"23721  "^ffff00ΦHillborn

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff3.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff12
^ffcb4aWeapon　^ffffffAxe, Poleaxe, Hammer, or Polehammer

^ffcb4aRequired Cultivation　^ffffffMaster of Harmony
Swing your weapon in a powerful arc, smashing
it into all enemies within ^96f5ff10^ffffff meters. Deals
base physical damage plus ^96f5ff165%%^ffffff of weapon damage
plus ^96f5ff7703^ffffff. Slows targets by ^96f5ff50%%^ffffff for ^96f5ff%d^ffffff seconds.

Has up to a ^96f5ff50%%^ffffff chance, based on your Soulforce,
to deal double base physical damage.

^f7dfa5Sage version has a ^96f5ff25%%^f7dfa5 chance to empower you for
^96f5ff10^f7dfa5 seconds, increasing your Critical Rate by ^96f5ff20%%^f7dfa5."23730  "ΩHillborn"23731  "^ffff00ΩHillborn

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff3.0　^ffcb4aseconds
^ffcb4aChi Gained　^ffffff12
^ffcb4aWeapon　^ffffffAxe, Poleaxe, Hammer, or Polehammer

^ffcb4aRequired Cultivation　^ffffffMaster of Discord
Swing your weapon in a powerful arc, smashing
it into all enemies within ^96f5ff10^ffffff meters. Deals
base physical damage plus ^96f5ff165%%^ffffff of weapon damage
plus ^96f5ff7703^ffffff. Slows targets by ^96f5ff50%%^ffffff for ^96f5ff%d^ffffff seconds.

Has up to a ^96f5ff50%%^ffffff chance, based on your Soulforce,
to deal double base physical damage.

^d618e7Demon version slows targets by ^96f5ff65%%^d618e7."23740  "ΦDragon Rising"23741  "^ffff00ΦDragon Rising

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff140^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.5　^ffcb4aseconds
^ffcb4aCooldown　^ffffff15.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Swing your weapon in a rising attack, dealing
base physical damage plus ^96f5ff105%%^ffffff of weapon damage
plus ^96f5ff5834^ffffff and stunning the target for ^96f5ff4^ffffff seconds.
Never misses

Axes, Poleaxes, Hammers and Polearms stun the target for ^96f5ff7^ffffff seconds.
Poleblades, Pikes and Clubs increases the range to ^96f5ff20^ffffff meters plus ^96f5ff100%%^ffffff of weapon damage
Blades and Swords reduces the channeling time to ^96f5ff0.2^ffffff seconds
and casting time to ^96f5ff1.4^ffffff seconds plus ^96f5ff300%%^ffffff of weapon damage.

^a6caf0Costs ^ffffff1^a6caf0 Spark.

^f7dfa5Sage version has a 35%% chance to consume no Sparks.^96f5ff^f7dfa5

"23750  "ΩDragon Rising"23751  "^ffff00ΩDragon Rising

^ffcb4aRange　^ffffffMelee
^ffcb4aMana　^96f5ff140^ffffff
^ffcb4aChannel　^ffffff0.4　^ffcb4aseconds
^ffcb4aCast　^ffffff1.5　^ffcb4aseconds
^ffcb4aCooldown　^ffffff15.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Swing your weapon in a rising attack, dealing
base physical damage plus ^96f5ff105%%^ffffff of weapon damage
plus ^96f5ff5834^ffffff and stunning the target for ^96f5ff4^ffffff seconds.
Never misses

Axes, Poleaxes, Hammers and Polearms stun the target for ^96f5ff7^ffffff seconds.
Poleblades, Pikes and Clubs increases the range to ^96f5ff20^ffffff meters and deals an additional of ^96f5ff100%%^ffffff of weapon damage
Blades and Swords reduces the channeling time to ^96f5ff0.2^ffffff seconds
and casting time to ^96f5ff1.4^ffffff seconds plus ^96f5ff300%%^ffffff of weapon damage.

^a6caf0Costs ^ffffff1^a6caf0 Spark.

^d618e7Sage version increases Paralysis duration by ^96f5ff1.5^d618e7 seconds.
"31930  "ΣReel In"31931  "^ffff00ΣReel In

^ffcb4aRange　^96f5ff25^ffffff　^ffcb4ameters
^ffcb4aMana　^96f5ff212^ffffff
^ffcb4aCast　^ffffff2.0　^ffcb4aseconds
^ffcb4aCooldown　^ffffff120.0　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons, Unarmed

^ffcb4aRequired Cultivation　^ffffffAware of Vacuity
Channel a line of energy from your weapon to pull
an enemy toward you. The success chance is ^96f5ff^ffffff^96f5ff100%%^ffffff.
　
^a6caf0Costs ^ffffff50^a6caf0 Chi.



"31940  "Φ Roar of the Pride"31941  "^ffff00ΦRoar of the Pride

^ffcb4aRange　^ffffff5　meters
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aChannel　^ffffff0.6　^ffcb4aseconds
^ffcb4aCast　^ffffff1.2　^ffcb4aseconds
^ffcb4aCooldown　^96f5ff%d^ffffff　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Myriad
Roar with fury, stunning all enemies within ^96f5ff10^ffffff meters for
^96f5ff6^ffffff seconds. ^96f5ffPrimal Sage version has the highest success rate.^ffffff
Also disarms all enemies within ^96f5ff10^ffffff meters for ^96f5ff6^ffffff seconds.

Polearms, Pikes, and Clubs: Increases cast range to ^96f5ff20^ffffff meters
and deals damage to a single target,
stunning and disarming them for ^96f5ff5^ffffff seconds.
Blades and Swords: Doesn't stun or disarm the enemies.
Reduces Channeling time to ^96f5ff0.1^ffffff seconds and Casting time to ^96f5ff1.0^ffffff second.
Enemies within ^96f5ff10^ffffff meters will be dealt ^96f5ff200%%^ffffff of base physical damage.
Cannot be a critical strike, but has a chance to
double your Critical Rate and deal ^96f5ff1.5^ffffff times damage.

^a6caf0Costs ^ffffff35^a6caf0 Chi.

^f7dfa5Sage version reduces Chi cost by ^96f5ff15^f7dfa5."31950  "ΩRoar of the Pride"31951  "^ffff00ΩRoar of the Pride

^ffcb4aRange　^ffffff5　meters
^ffcb4aMana　^96f5ff%d^ffffff
^ffcb4aChannel　^ffffff0.6　^ffcb4aseconds
^ffcb4aCast　^ffffff1.2　^ffcb4aseconds
^ffcb4aCooldown　^96f5ff%d^ffffff　^ffcb4aseconds
^ffcb4aWeapon　^ffffffMelee weapons

^ffcb4aRequired Cultivation　^ffffffAware of the Void
Roar with fury, stunning all enemies within ^96f5ff10^ffffff meters for
^96f5ff6^ffffff seconds. ^96f5ffPrimal Sage version has the highest success rate.^ffffff
Also disarms all enemies within ^96f5ff10^ffffff meters for ^96f5ff6^ffffff seconds.

Polearms, Pikes, and Clubs: Increases cast range to ^96f5ff20^ffffff meters
and deals damage to a single target,
stunning and disarming them for ^96f5ff5^ffffff seconds.
Blades and Swords: Doesn't stun or disarm the enemies.
Reduces Channeling time to ^96f5ff0.1^ffffff seconds and Casting time to ^96f5ff1.0^ffffff second.
Enemies within ^96f5ff10^ffffff meters will be dealt ^96f5ff200%%^ffffff of base physical damage.
Cannot be a critical strike, but has a chance to
double your Critical Rate and deal ^96f5ff1.5^ffffff times damage.

^a6caf0Costs ^ffffff35^a6caf0 Chi.

^d618e7Demon version reduces the cooldown by ^96f5ff1^d618e7 second, and always succeeds."*/
/* SKILL DESCRIPTION END */

#ifndef __CPPGEN_GNET_SKILL195
#define __CPPGEN_GNET_SKILL195
namespace GNET
{
#ifdef _SKILL_SERVER
    class Skill195:public Skill
    {
        public:
        enum
        { SKILL_ID = 195 };
        Skill195 ():Skill (SKILL_ID)
        {
        }
    };
#endif
    class Skill195Stub:public SkillStub
    {
        public:
#ifdef _SKILL_SERVER
        class State1:public SkillStub::State
        {
            public:
            int GetTime (Skill * skill) const
            {
                return 200;
            }
            bool Quit (Skill * skill) const
            {
                return false;
            }
            bool Loop (Skill * skill) const
            {
                return false;
            }
            bool Bypass (Skill * skill) const
            {
                return false;
            }
            void Calculate (Skill * skill) const
            {
                skill->GetPlayer ()->SetDecmp (0.2 * (-1.6 + 4 * skill->GetLevel ()));
                skill->GetPlayer ()->SetPray (1);
            }
            bool Interrupt (Skill * skill) const
            {
                return false;
            }
            bool Cancel (Skill * skill) const
            {
                return 1;
            }
            bool Skip (Skill * skill) const
            {
                return 0;
            }
        };
#endif
#ifdef _SKILL_SERVER
        class State2:public SkillStub::State
        {
            public:
            int GetTime (Skill * skill) const
            {
                return 800;
            }
            bool Quit (Skill * skill) const
            {
                return false;
            }
            bool Loop (Skill * skill) const
            {
                return false;
            }
            bool Bypass (Skill * skill) const
            {
                return false;
            }
            void Calculate (Skill * skill) const
            {
                skill->GetPlayer ()->SetDecmp (0.8 * (-1.6 + 4 * skill->GetLevel ()));
                skill->SetPlus (0);
                skill->SetRatio (0);
                skill->SetDamage (skill->GetAttack ());
                skill->GetPlayer ()->SetPerform (1);
            }
            bool Interrupt (Skill * skill) const
            {
                return false;
            }
            bool Cancel (Skill * skill) const
            {
                return 0;
            }
            bool Skip (Skill * skill) const
            {
                return 0;
            }
        };
#endif
#ifdef _SKILL_SERVER
        class State3:public SkillStub::State
        {
            public:
            int GetTime (Skill * skill) const
            {
                return 0;
            }
            bool Quit (Skill * skill) const
            {
                return false;
            }
            bool Loop (Skill * skill) const
            {
                return false;
            }
            bool Bypass (Skill * skill) const
            {
                return false;
            }
            void Calculate (Skill * skill) const
            {
            }
            bool Interrupt (Skill * skill) const
            {
                return false;
            }
            bool Cancel (Skill * skill) const
            {
                return 0;
            }
            bool Skip (Skill * skill) const
            {
                return 0;
            }
        };
#endif
        Skill195Stub ():SkillStub (195)
        {
            cls                 = 4;
#ifdef _SKILL_CLIENT
            name                = L"��ɱ";
            nativename          = "��ɱ";
            icon                = "��ɱ.dds";
#endif
            max_level           = 10;
            type                = 1;
            apcost              = 0;
            arrowcost           = 0;
            apgain              = 5;
            attr                = 1;
            rank                = 0;
            eventflag           = 4;
            is_senior           = 0;
            posdouble           = 0;
            clslimit            = 0;
            time_type           = 0;
            showorder           = 1502;
            allow_land          = 1;
            allow_air           = 1;
            allow_water         = 1;
            allow_ride          = 0;
            auto_attack         = 0;
            long_range          = 0;
            restrict_corpse     = 0;
            allow_forms         = 1;
            {
                restrict_weapons.push_back (9);
            }
#ifdef _SKILL_CLIENT
            effect              = "��ɱ.sgc";
#endif
            range.type          = 0;
            doenchant           = true;
            dobless             = false;
            commoncooldown      = 0;
            commoncooldowntime  = 0;
            pre_skills.push_back (std::pair < ID, int >(102, 1));
#ifdef _SKILL_CLIENT
            aerial_effect       = "";
            gfxfilename         = "";
            gfxhangpoint        = "0";
#endif
#ifdef _SKILL_SERVER
            statestub.push_back (new State1 ());
            statestub.push_back (new State2 ());
            statestub.push_back (new State3 ());
#endif
        }
        virtual ~ Skill195Stub ()
        {
        }
        float GetMpcost (Skill * skill) const
        {
            static float aarray[10] = { 2,6,10,14,18,22,26,30,34,38 };
            return aarray[skill->GetLevel () - 1];
        }
        int GetExecutetime (Skill * skill) const
        {
            return 800;
        }
        int GetCoolingtime (Skill * skill) const
        {
            return 8000;
        }
        int GetRequiredLevel (Skill * skill) const
        {
            static int aarray[10] = { 3,8,13,18,23,28,33,38,43,48 };
            return aarray[skill->GetLevel () - 1];
        }
        int GetRequiredSp (Skill * skill) const
        {
            static int aarray[10] = { 100,800,2100,4100,7000,10900,16100,23000,32000,44100 };
            return aarray[skill->GetLevel () - 1];
        }
        float GetRadius (Skill * skill) const
        {
            return (float) (0);
        }
        float GetAttackdistance (Skill * skill) const
        {
            return (float) (0);
        }
        float GetAngle (Skill * skill) const
        {
            return (float) (1 - 0.0111111 * (0));
        }
        float GetPraydistance (Skill * skill) const
        {
            return (float) (skill->GetPlayer ()->GetRange ());
        }
#ifdef _SKILL_CLIENT
        int GetIntroduction (Skill * skill, wchar_t * buffer, int length, wchar_t * format) const
        {
            return _snwprintf (buffer, length, format,
            skill->GetLevel (),
            -1.6 + 4 * skill->GetLevel (), 4.8 * skill->GetLevel () * skill->GetLevel () + 103 * skill->GetLevel () + 72.5);
            
        }
#endif
#ifdef _SKILL_SERVER
        int GetEnmity (Skill * skill) const
        {
            return 0;
        }
#endif
#ifdef _SKILL_SERVER
        bool StateAttack (Skill * skill) const
        {
            skill->GetVictim ()->SetProbability (1.0 * 100);
            skill->GetVictim ()->SetTime (15000);
            skill->GetVictim ()->SetAmount (4.8 * skill->GetLevel () * skill->GetLevel () + 103 * skill->GetLevel () + 72.5);
            skill->GetVictim ()->SetBleeding (1);
            return true;
        }
#endif
#ifdef _SKILL_SERVER
        bool TakeEffect (Skill * skill) const
        {;
            return true;
        }
#endif
#ifdef _SKILL_SERVER
        float GetEffectdistance (Skill * skill) const
        {
            return (float) (12.5);
        }
#endif
#ifdef _SKILL_SERVER
        int GetAttackspeed (Skill * skill) const
        {
            return 3;
        }
#endif
#ifdef _SKILL_SERVER
        float GetHitrate (Skill * skill) const
        {
            return (float) (1.2 + 0.05 * skill->GetLevel ());
        }
#endif
    };
}
#endif